name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81 
          mkdir -p cypress/reports/mocha/Regression # Ensure path exists
          echo "Sample Mocha Report" > cypress/reports/mocha/Regression/report.html

      # Step 5: Cache Mocha reports
      - name: Cache Mocha Reports
        uses: actions/cache@v3
        with:
          path: cypress/reports/mocha/
          key: mocha-reports-${{ github.run_id }}
          restore-keys: mocha-reports-

  error-handler:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: ${{ failure() }} # Runs only if any upstream job (cypress-run) fails
    steps:
      # Step 1: Restore cached Mocha reports
      - name: Restore Mocha Reports from Cache
        uses: actions/cache@v3
        with:
          path: cypress/reports/mocha/
          key: mocha-reports-${{ github.run_id }}
          restore-keys: mocha-reports-

      # Step 2: Debug directory contents
      - name: Debug Mocha Reports
        run: |
          echo "Mocha Reports Directory Contents:"
          ls -R cypress/reports/mocha/

      # Step 3: Run Error Handler
      - name: Run Error Handler
        run: |
          echo "Setting up Node.js environment..."
          node -v || (echo "Node.js not found, setting it up..." && nvm install 16)

          echo "Installing dependencies..."
          cd ./failure-analysis-automation
          npm install
          ls -la cypress

          GITHUB_RUN_ID="${{ github.run_id }}"
          echo "GitHub Run ID: $GITHUB_RUN_ID"
          
          npx ts-node cypress/errorHandler.ts
