name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests and capture runId
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81 
          
      - name: List all files and directories
        run: |
          echo "Checking current working directory..."
          pwd
          echo "Listing all files and directories in the current directory..."
          ls -al
          echo "Recursive listing of all files and directories..."
          find . -type d -print -exec ls -al {} \;

  error-handler:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download artifacts (Optional: in case Cypress output is needed)
      - name: Download Cypress Output
        uses: actions/download-artifact@v3
        with:
          name: cypress-output

      # Step 3: Run error handler
      - name: Run Error Handler
        run: |
          echo "Debug: Checking current directory"
          pwd
          echo "Debug: Listing contents of current directory"
          ls -la

          echo "Setting up Node.js environment..."
          node -v || (echo "Node.js not found, setting it up..." && nvm install 16)

          echo "Installing dependencies..."
          cd ./failure-analysis-automation
          npm install

          echo "Running error handler for failures..."
          RUN_ID=$(echo "$GITHUB_STEP_SUMMARY" | grep -o 'https://cloud.cypress.io/projects/[^ ]*/runs/[0-9]*' | grep -o '[0-9]*')
          echo "run id: $RUN_ID"
          CYPRESS_RUN_NUMBER=$(grep -o 'https://cloud.cypress.io/projects/[^ ]*/runs/[0-9]*' ../cypress-output.log | grep -o '[0-9]*$' || echo "not_found")
          echo "Cypress Run Number: $CYPRESS_RUN_NUMBER"

          npx ts-node cypress/errorHandler.ts blitz Regression $CYPRESS_RUN_NUMBER wrt
