name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    outputs:
      report-path: ${{ steps.set-report-path.outputs.report-path }}  # Output the report path for the next job
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81 
          echo "Listing reports directory"
          ls -la cypress/reports
          echo "Listing mocha/Regression directory"
          ls -la cypress/reports/mocha/Regression/.jsons

      - name: Confirm current working directory
        run: pwd

      # Step 5: Upload Mocha Reports as an artifact
      - name: Upload Mocha Reports Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mocha-reports
          path: cypress/reports/mocha/Regression/.jsons
          if-no-files-found: warn
          include-hidden-files: false
