name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    outputs:
      report-path: ${{ steps.set-report-path.outputs.report-path }}  # Output the report path for the next job
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81 
          echo "Listing reports directory"
          ls -la cypress/reports
          echo "Listing mocha/Regression directory"
          ls -la cypress/reports/mocha/Regression/.jsons
          
      # Step 5: Set the report path for the next job using environment files
      - name: Set Report Path
        id: set-report-path
        run: echo "REPORT_PATH=$(pwd)/cypress/reports/mocha/Regression/.jsons" >> $GITHUB_ENV

  error-handler:
    runs-on: ubuntu-latest
    needs: cypress-run  # Ensure this job runs after the cypress-run job
    if: ${{ always() }}  # Runs only if any upstream job (cypress-run) fails
    steps:
      # Step 1: Create the required directory in the next job (ensure write access)
      - name: Create report directory
        run: |
          echo "Creating report directory..."
          mkdir -p cypress/reports/mocha/Regression/.jsons
          chmod -R 755 cypress/reports/mocha/Regression/.jsons  # Ensure write access

      # Step 2: Copy Mocha Reports from the previous job's output
      - name: Copy Mocha Report
        run: |
          echo "Copying reports from: $REPORT_PATH"
          ls -la $REPORT_PATH  # Debug: List contents of $REPORT_PATH
          cp -R $REPORT_PATH/* cypress/reports/mocha/Regression/.jsons

      # Step 3: Debug directory contents
      - name: Debug Mocha Reports
        run: |
          echo "Mocha Reports Directory Contents:"
          ls -R cypress/reports/mocha/Regression/.jsons

      # Step 4: Run Error Handler
      - name: Run Error Handler
        run: |
          echo "Setting up Node.js environment..."
          node -v || (echo "Node.js not found, setting it up..." && nvm install 16)
          echo "Installing dependencies..."
          cd ./failure-analysis-automation
          npm install
          ls -la cypress
          GITHUB_RUN_ID="${{ github.run_id }}"
          echo "GitHub Run ID: $GITHUB_RUN_ID"
          
          npx ts-node cypress/errorHandler.ts
