name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81
          echo "Listing reports directory"
          ls -la cypress/reports
          echo "Listing mocha/Regression directory"
          ls -la cypress/reports/mocha/Regression/.jsons

      # Step 4: Create Zip Archive of Mocha Reports
      - name: Create Zip Archive of Mocha Reports
        run: |
          mkdir -p cypress/reports/mocha/Regression/.json/archive
          zip -r cypress/reports/mocha/Regression/.json/archive/mocha-reports.zip cypress/reports/mocha/Regression/.jsons/report*.json

      # Step 5: Upload Mocha Reports as Zip if the tests fail
      - name: Upload Mocha Reports as Zip
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: mocha-reports
          path: cypress/reports/mocha/Regression/.json/archive/mocha-reports.zip
