name: Run Cypress Tests and Handle Failures
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select Test Type'
        type: choice
        options:
          - Smoke
          - Regression
          - Sanity
      cloud_record:
        description: 'Cypress cloud record'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [ 1 ]
    steps:
      - name: Run Cypress tests
        env:
          IS_SCHEDULED_EVENT: ${{ github.event_name == 'schedule' }}
        run: |
          echo "Running tests for container: ${{ matrix.container }}"
          echo "Value of IS_SCHEDULED_EVENT: $IS_SCHEDULED_EVENT"
          exit 1 # Simulating a failure for demonstration purposes

  error-handler:
    needs: [cypress-run]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Capture env variables & Run Error Handler script
        run: |
          # Conditionally execute sleep if previous jobs failed
          if [[ "${{ needs.cypress-run.result }}" == "failure" ]]; then
            echo "Previous job failed. Executing failure handler..."
            sleep 240
          fi
