name: Run Cypress Tests and List Artifacts

on:
  schedule:
    - cron: '* * * * *' # Runs every 2 minutes
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select Test Type'
        type: choice
        options:
          - Smoke
          - Regression
          - Sanity
      cloud_record:
        description: 'Cypress cloud record'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

jobs:
  calculate-containers-count:
    runs-on: ubuntu-latest
    outputs:
      default_containers: ${{ steps.set-default.outputs.default_containers }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set default containers
        id: set-default
        run: |
          cloud_record=${{ github.event.inputs.cloud_record || 'true' }}
          environment_name="${{ github.event.inputs.environment_name }}"
          if [[ "$cloud_record" == "true" && "$environment_name" == "production" ]]; then
            regions=$(cat sanity-test-config.json)
            default_containers=$(echo "$regions" | jq -c '[.regions[]]')
            echo "default_containers=$default_containers" >> $GITHUB_ENV  # Using GITHUB_ENV for passing to subsequent jobs
          else
            echo "default_containers=[1,2,3,4,5]" >> $GITHUB_ENV  # Hardcoded values if not production
          fi

  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-default.outputs.env_name }}
    steps:
      - name: Set default environment name
        id: set-default
        run: |
          current_hour=$(date +"%H")
          if [[ -z "${{ inputs.environment_name }}" ]]; then
            echo "Hour Now: $current_hour"
            if [[ "$current_hour" == "14" ]]; then
              echo "env_name=blitzv2" >> $GITHUB_OUTPUT
            elif [[ "$current_hour" == "15" ]]; then
              echo "env_name=stagev2" >> $GITHUB_OUTPUT
            else
              echo "env_name=default_env" >> $GITHUB_OUTPUT
            fi
          else
            echo "env_name=${{ inputs.environment_name }}" >> $GITHUB_OUTPUT

  cypress-run:
    needs: [determine-environment, calculate-containers-count]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ${{ fromJSON(needs.calculate-containers-count.outputs.default_containers) }}
    steps:
      - name: Run Cypress tests
        run: |
          echo "Running tests for container: ${{ matrix.container }}"
