name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81
          echo "Listing reports directory"
          ls -la cypress/reports
          echo "Listing mocha/Regression directory"
          ls -la cypress/reports/mocha/Regression/.jsons

      # Step 4: Upload Mocha Reports as an artifact
      - name: Upload JSON Files as Artifact
        run: |
          files=$(find cypress/reports/mocha/Regression/.jsons -type f -name "*.json")
          if [ -z "$files" ]; then
            echo "No JSON files found"
            exit 1
          else
            echo "Found JSON files:"
            echo "$files"
            for file in $files; do
              echo "Uploading $file"
              # Use the upload-artifact action to upload each file
              echo "artifact=$file" >> $GITHUB_ENV
            done
          fi
