name: Run Cypress Tests and List Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  # Job to run Cypress tests and upload artifacts
  cypress-run:
    env:
      CYPRESS_PROJECT_ID: 'qdjmfg'
      CYPRESS_RECORD_KEY: '349e203f-44fe-4e1c-91b4-1869bd99af81'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2]
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Cypress tests
      - name: Cypress Run for Matrix Container
        uses: cypress-io/github-action@v6
        with:
          record: 'true'
          parallel: 'true'
          browser: 'chrome'
        env:
          MATRIX_CONTAINER: ${{ matrix.container }}

      # Step 3: Verify Report Files
      - name: Verify Report Files
        if: ${{ always() }}
        run: |
          echo "Checking reports directory for container ${{ matrix.container }}..."
          ls -l cypress/reports/mocha/Regression/${{ matrix.container }}/.jsons || echo "Directory or files not found."

      # Step 4: Create Zip Archive of Mocha Reports
      - name: Zip Mocha Report Files
        if: ${{ always() }}
        run: |
          mkdir -p zipped-reports
          if [ -d "cypress/reports/mocha/Regression/${{ matrix.container }}/.jsons" ]; then
            zip -r zipped-reports/mocha-reports-${{ matrix.container }}.zip cypress/reports/mocha/Regression/${{ matrix.container }}/.jsons/*
          else
            echo "No files to zip for container ${{ matrix.container }}."
          fi

      # Step 5: Upload Artifacts
      - name: Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.container }}
          retention-days: 1
          path: zipped-reports/mocha-reports-${{ matrix.container }}.zip

  # Job to download and list artifacts
  download-artifacts:
    if: ${{ always() }}
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out repository to access the JavaScript script
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Step 1: Create a directory to download artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: downloaded-artifacts
          
      - name: Unzip Artifacts
        run: |
          for dir in downloaded-artifacts/*; do
            if [ -d "$dir" ]; then
              echo "Unzipping $dir..."
              unzip -o "$dir/*.zip" -d "$dir/unzipped"
            fi
          done

      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify a compatible Node.js version

      # Step 2: Debug the downloaded directory
      - name: Debug directory contents
        run: ls -la /home/runner/work/cypressmetrics/cypressmetrics/downloaded-artifacts

      # Step 4: List the contents of downloaded artifacts
      - name: List Downloaded Artifacts
        run: |
          echo "Listing contents of directory: /home/runner/work/cypressmetrics/cypressmetrics/downloaded-artifacts"
          node listArtifacts.js ./downloaded-artifacts
