name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:    
  cypress-run:
    env: 
        CYPRESS_PROJECT_ID: 'qdjmfg'
        CYPRESS_RECORD_KEY: '349e203f-44fe-4e1c-91b4-1869bd99af81'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2]
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Cypress run for Account-Admin
        uses: cypress-io/github-action@v6
        with:
          record: 'true'
          parallel: 'true'
          browser: 'chrome'
      # Step 4: Create Zip Archive of Mocha Reports
      - name: Zip Mocha Report Files
        if: ${{ always() }}  
        run: |
          mkdir -p zipped-reports
          zip -r zipped-reports/mocha-reports-${{ matrix.container }}.zip cypress/reports/mocha/Regression/.jsons/*
          
      - name: Upload Artifacts if Test Failed
        if: ${{ always() }}  
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.container }}
          retention-days: 1 ## After 24 hours the artifacts will be automatically cleanedup since there are only needed for slack alerting.
          path: zipped-reports/mocha-reports-${{ matrix.container }}.zip
