name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    outputs:
      report-path: ${{ steps.set-report-path.outputs.report-path }}  # Output the report path for the next job
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests and generate Mocha reports
      - name: Run Cypress tests
        id: cypress-run
        run: |
          npx cypress run --record --key 349e203f-44fe-4e1c-91b4-1869bd99af81 
          echo "Listing reports directory"
          ls -la cypress/reports
          echo "Listing mocha/Regression directory"
          ls -la cypress/reports/mocha/Regression/.jsons

      # Step 5: Upload Mocha Reports as an artifact
      - name: Upload Mocha Reports Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mocha-reports
          path: cypress/reports/mocha/Regression/.jsons  # Path to the generated report files

  error-handler:
    runs-on: ubuntu-latest
    needs: cypress-run  # Ensure this job runs after the cypress-run job
    if: ${{ always() }}  # Runs only if any upstream job (cypress-run) fails
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download Mocha Reports Artifact from the previous job
      - name: Download Mocha Reports Artifact
        uses: actions/download-artifact@v3
        with:
          name: mocha-reports
          path: ./cypress/reports/mocha/Regression/  # Path to download the artifact to

      # Step 3: Debug the downloaded report directory
      - name: Debug Mocha Reports Directory
        run: |
          echo "Mocha Reports Directory Contents:"
          ls -R ./cypress/reports/mocha/Regression/

      # Step 4: Run Error Handler
      - name: Run Error Handler
        run: |
          echo "Setting up Node.js environment..."
          node -v || (echo "Node.js not found, setting it up..." && nvm install 16)
          echo "Installing dependencies..."
          cd ./failure-analysis-automation
          npm install
          ls -la cypress
          GITHUB_RUN_ID="${{ github.run_id }}"
          echo "GitHub Run ID: $GITHUB_RUN_ID"
          
          npx ts-node cypress/errorHandler.ts
