name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-rules:
    name: Check PR Body, Branch & Title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
  
            // One shared pattern for both branch name and PR title
            const pattern = /^[a-zA-Z0-9]+\/[A-Z]{1,5}-\d+-[a-z0-9-]+$/;
  
            // ---------- Branch name check ----------
            if (!pattern.test(pr.data.head.ref)) {
              throw new Error(`❌ Branch name "${pr.data.head.ref}" must match: githubusername/TICKETID-short-description`);
            }
  
            // ---------- PR title check ----------
            if (!pattern.test(pr.data.title)) {
              throw new Error(`❌ PR title "${pr.data.title}" must match: githubusername/TICKETID-short-description`);
            }
