name: Run Karate Tests

on:
  schedule:
    - cron: '39 8 * * *' # blitzv2 -> 2:09 PM IST
    - cron: '44 8 * * *' # stagev2 -> 2:14 PM IST

jobs:
  determine-environment:
    runs-on: ubuntu-latest

    outputs:
      env_name: ${{ steps.set-default.outputs.env_name }}

    steps:
      - name: Set environment name
        id: set-default
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Triggered Schedule: ${{ github.event.schedule }}"

          if [[ "${{ github.event_name }}" == "schedule" ]]; then

            if [[ "${{ github.event.schedule }}" == "39 8 * * *" ]]; then
              echo "Detected blitzv2 scheduled run"
              echo "env_name=blitzv2" >> $GITHUB_OUTPUT

            elif [[ "${{ github.event.schedule }}" == "44 8 * * *" ]]; then
              echo "Detected stagev2 scheduled run"
              echo "env_name=stagev2" >> $GITHUB_OUTPUT

            else
              echo "Unknown schedule detected"
              exit 1
            fi

          fi

          echo "Final environment:"
          cat $GITHUB_OUTPUT

      - name: Print selected environment
        run: |
          echo "Selected env: ${{ steps.set-default.outputs.env_name }}"
